name: covid
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - blas=1.0=mkl
  - brotli=1.2.0=h27d5ac6_0
  - brotli-bin=1.2.0=h1421c7b_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2025.12.2=h06a4308_0
  - contourpy=1.0.5=py38hdb19cb5_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.3=h7354ed3_4
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fsspec=2024.10.0=pyhff2d567_0
  - future=1.0.0=pyhd8ed1ab_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - grpcio=1.51.1=py38h7dc2bf5_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jpeg=9b=h024ee3a_2
  - kiwisolver=1.4.4=py38h6a678d5_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libabseil=20220623.0=cxx17_h05df665_6
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.51.1=h05bd8bd_0
  - libiconv=1.16=h5eee18b_3
  - libpng=1.6.50=h2ed474d_0
  - libprotobuf=3.21.12=hfc55251_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.2.0=h85742a9_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib=3.7.2=py38h06a4308_0
  - matplotlib-base=3.7.2=py38h1128e8f_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - ncurses=6.5=h7934f7d_0
  - ninja-base=1.13.1=h0f57076_0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openssl=1.1.1w=hd590300_0
  - packaging=24.1=py38h06a4308_0
  - pcre2=10.46=hf426167_0
  - pillow=9.3.0=py38hace64e9_1
  - pip=24.2=py38h06a4308_0
  - protobuf=4.21.12=py38h8dc9893_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pydeprecate=0.3.2=pyhd8ed1ab_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.18=h7a1cb2a_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python_abi=3.8=2_cp38
  - pytorch=1.7.1=py3.8_cuda10.2.89_cudnn7.6.5_0
  - pytorch-lightning=1.5.10=pyhd8ed1ab_0
  - pyyaml=6.0.2=py38h2019614_0
  - qt=5.9.7=h5867ecd_1
  - re2=2022.06.01=h27087fc_1
  - readline=8.3=hc2a1206_0
  - setuptools=59.5.0=py38h578d9bd_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.51.0=h2a70700_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.17.1=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py38h52d8a92_1
  - tk=8.6.15=h54e0aa7_0
  - torchaudio=0.7.2=py38
  - torchmetrics=0.10.3=pyhd8ed1ab_0
  - torchvision=0.8.2=py38_cu102
  - tornado=6.4.1=py38h5eee18b_0
  - tqdm=4.66.5=py38h2f386ee_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - werkzeug=3.0.6=pyhd8ed1ab_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.4.9=haebb681_0
  - pip:
      - ninja==1.13.0
      - sru==2.6.0
prefix: /home/alireza/anaconda3/envs/covid
